/**
 * Coaching Domain Types
 *
 * Types for the Claude-as-coach feedback loop:
 * coaching cues, athlete reactions, and compliance tracking.
 */

/**
 * A coaching cue generated by Claude during a workout session.
 */
export interface CoachingCue {
  /** Unique cue identifier */
  id: string;

  /** The coaching message displayed to the athlete */
  message: string;

  /** Suggested load adjustment in lbs (positive = add, negative = drop, 0 = maintain) */
  suggestedLoadDelta: number;

  /** Suggested absolute weight, if applicable */
  suggestedWeight: number | null;

  /** Set index this cue was generated after (0-based) */
  afterSetIndex: number;

  /** Timestamp when the cue was generated */
  generatedAt: number;
}

/**
 * Athlete reaction to a coaching cue.
 */
export type CueReaction = 'thumbs_up' | 'thumbs_down' | null;

/**
 * A coaching cue with the athlete's reaction attached.
 */
export interface ReactedCue extends CoachingCue {
  reaction: CueReaction;
  reactedAt: number | null;
}

/**
 * Whether the athlete followed the coaching advice.
 */
export type ComplianceOutcome =
  | 'followed' // Used the suggested weight
  | 'ignored' // Stayed at original weight
  | 'partial' // Moved toward suggestion but not fully
  | 'unknown'; // No completed set to compare

/**
 * Tracks whether a coaching cue was followed and what happened.
 */
export interface CueComplianceRecord {
  /** The cue that was given */
  cue: ReactedCue;

  /** Whether the athlete followed the suggestion */
  compliance: ComplianceOutcome;

  /** Weight used in the set after the cue */
  actualWeight: number | null;

  /** Mean velocity of the set after the cue */
  actualVelocity: number | null;

  /** Mean velocity of the set before the cue (for comparison) */
  previousVelocity: number | null;

  /** Human-readable summary of what happened */
  summary: string;
}

/**
 * Structured context for Claude API calls, including feedback history.
 */
export interface CoachingContext {
  /** Exercise being performed */
  exerciseName: string;

  /** Training goal */
  goal: string;

  /** Current set index (0-based) */
  currentSetIndex: number;

  /** Total planned sets */
  totalSets: number;

  /** Summary of completed sets: weight, reps, mean velocity */
  completedSetsSummary: string[];

  /** Previous coaching cues with compliance outcomes */
  previousCueFeedback: string[];

  /** Auto-regulation signals (load suggestion, velocity warning) */
  autoRegulationContext: string | null;

  cueStyle: 'brief' | 'detailed';
}
